// src/builders/html.js
// AGNI HTML Builder  v1.9.1
//
// Compiles a parsed OLS lesson object into a single HTML lesson file
// plus supporting assets in the same output directory.
//
// Changes from v1.9.0:
//   [Phase 4] Embeds OLS_PUBLIC_KEY in the compiled HTML alongside the
//     existing OLS_SIGNATURE and OLS_INTENDED_OWNER globals. The public
//     key is read from options.publicKey (path to PEM file) at build time,
//     exported as SPKI DER, and base64-encoded for embedding.
//     player.js verifyIntegrity() imports it with SubtleCrypto format:'spki'.
//   [Phase 4] signContent() call updated — html.js now passes options.privateKey
//     as a file path (unchanged) and the returned base64 signature is embedded
//     as OLS_SIGNATURE (unchanged). No breaking changes to the signing side.
//   - Version bumped to 1.9.1.
//
// Output structure:
//   dist/
//     gravity.html              — lesson HTML (inlines factory-loader + player)
//     gravity-ir.json           — metadata sidecar for theta engine
//     shared-runtime.js         — cached shared asset (loaded by factory-loader)
//     katex-core.css            — KaTeX layout rules (written if lesson has equations)
//     katex-symbols-{x}.css    — per-domain symbol subsets (written as needed)
//     katex-fonts.css           — KaTeX @font-face rules (written if lesson has equations)
//
// Load order in the browser (enforced by factory-loader.js):
//   1. factory-loader.js (inline)   — AGNI_LOADER bootstrap
//   2. LESSON_DATA (inline)         — lesson IR + factory manifest
//   3. player.js (inline)           — calls AGNI_LOADER.loadDependencies()
//   4. shared-runtime.js (fetched)  — AGNI_SHARED
//   5. svg-stage.js (fetched)       — AGNI_SVG.stage
//   6. svg-factories*.js (fetched)  — AGNI_SVG factory functions
//   7. svg-registry.js (fetched)    — AGNI_SVG.fromSpec()
//   8. table-renderer.js (fetched)  — if lesson has tables + visuals
//
// Runtime integrity globals written into the HTML (Phase 4):
//   window.OLS_SIGNATURE       base64 Ed25519 signature over the binding hash
//   window.OLS_PUBLIC_KEY      base64 SPKI DER Ed25519 public key (44 bytes)
//   window.OLS_INTENDED_OWNER  UUID of the intended device
//
// Target: Node.js 14+. Not loaded on the edge device.
// ─────────────────────────────────────────────────────────────────────────────

'use strict';

var fs   = require('fs');
var path = require('path');

var signContent        = require('../utils/crypto').signContent;
var ensureDir          = require('../utils/io').ensureDir;
var compiler           = require('../compiler');
var lessonAssembly     = require('../services/lessonAssembly');
var buildLessonIR      = compiler.buildLessonIR;
var buildLessonSidecar = compiler.buildLessonSidecar;
var buildKatexCss      = require('../utils/katex-css-builder').buildKatexCss;


// ─────────────────────────────────────────────────────────────────────────────
// Phase 4 helper: export the Hub's Ed25519 public key as base64 SPKI DER.
//
// Node.js exports Ed25519 public keys as SPKI DER by default when you call
// key.export({ type: 'spki', format: 'der' }). We base64-encode that for safe
// embedding in a JS string literal.
//
// SubtleCrypto in the browser expects SPKI format when importing Ed25519 keys.
// Do NOT strip the DER header and embed raw bytes — you'll import the wrong key.
//
// @param  {string} publicKeyPath  path to PEM-encoded Ed25519 public key
// @returns {string|null}          base64 SPKI DER, or null on error
// ─────────────────────────────────────────────────────────────────────────────
function readPublicKeySpki(publicKeyPath) {
  if (!publicKeyPath) return null;
  try {
    var crypto     = require('crypto');
    var pemContent = fs.readFileSync(publicKeyPath, 'utf8');
    // createPublicKey + export gives us the canonical SPKI DER regardless of
    // whether the source PEM was generated by openssl or node's generateKeyPair.
    var keyObject  = crypto.createPublicKey({ key: pemContent, format: 'pem' });
    var derBuffer  = keyObject.export({ type: 'spki', format: 'der' });
    return derBuffer.toString('base64');
  } catch (err) {
    console.warn('\u26A0\uFE0F  Could not read public key: ' + err.message);
    return null;
  }
}


/**
 * Builds a lesson HTML file, lesson-ir.json sidecar, and CSS assets from a
 * parsed OLS lesson object.
 *
 * @param {object} lessonData   parsed YAML lesson object
 * @param {object} options      CLI options: output, deviceId, privateKey,
 *                              publicKey, dev
 *                              options.publicKey  path to Ed25519 public key PEM
 *                                (new in v1.9.1, required for Phase 4 verification)
 */
async function buildHtml(lessonData, options) {
  console.log('[HTML] Building lesson:', (lessonData.meta && lessonData.meta.title) || 'Unnamed');
  console.log('[HTML] Device:', options.deviceId || 'Unbound (Development Mode)');

  // -- 1. Build the canonical IR -----------------------------------------------
  var ir = await buildLessonIR(lessonData, options);

  // -- 2. Write lesson-ir.json sidecar -----------------------------------------
  var outputDir   = path.dirname(options.output);
  var sidecar     = buildLessonSidecar(ir);
  var sidecarPath = options.output.replace(/\.html$/, '-ir.json');
  ensureDir(outputDir);
  fs.writeFileSync(sidecarPath, JSON.stringify(sidecar, null, 2));
  console.log('[HTML] Sidecar written:', sidecarPath);

  // -- 3. Write KaTeX CSS assets -----------------------------------------------
  buildKatexCss(ir.inferredFeatures.katexAssets, outputDir);

  // -- 4. Read runtime files ---------------------------------------------------
  var runtimeDir = path.join(__dirname, '../runtime');

  var playerJs        = fs.readFileSync(path.join(runtimeDir, 'player.js'),         'utf8');
  var factoryLoaderJs = fs.readFileSync(path.join(runtimeDir, 'factory-loader.js'), 'utf8');
  var styles          = fs.readFileSync(path.join(runtimeDir, 'style.css'),          'utf8');

  // -- 5a. binary-utils.js (load before shared-runtime; Backlog task 13) -------
  var binaryUtilsOutput = path.join(outputDir, 'binary-utils.js');
  var binaryUtilsSource = path.join(runtimeDir, 'binary-utils.js');
  if (fs.existsSync(binaryUtilsSource)) {
    fs.writeFileSync(binaryUtilsOutput, fs.readFileSync(binaryUtilsSource, 'utf8'));
  }

  // -- 5b. Handle shared-runtime.js (write once, reuse across lessons) -------
  var sharedOutput = path.join(outputDir, 'shared-runtime.js');
  var sharedSource = path.join(runtimeDir, 'shared-runtime.js');

  var shouldWriteShared = false;
  if (!fs.existsSync(sharedOutput)) {
    shouldWriteShared = true;
    console.log('[HTML] Shared runtime missing -> generating');
  } else {
    var sourceStat = fs.statSync(sharedSource);
    var destStat   = fs.statSync(sharedOutput);
    if (sourceStat.mtimeMs > destStat.mtimeMs) {
      shouldWriteShared = true;
      console.log('[HTML] Shared runtime source newer -> updating');
    }
  }

  if (shouldWriteShared) {
    var sharedCode = fs.readFileSync(sharedSource, 'utf8');
    fs.writeFileSync(sharedOutput, sharedCode);
    console.log('[HTML] Shared runtime written:', sharedOutput);
  } else {
    console.log('[HTML] Shared runtime up-to-date');
  }

  // -- 6. Build the factory dependency list ------------------------------------
  // binary-utils.js first (sets OLS_BINARY), then shared-runtime.js (AGNI_SHARED).
  var RUNTIME_VERSION = '1.9.1';

  var factoryDeps = [];
  if (fs.existsSync(binaryUtilsSource)) {
    factoryDeps.push({ file: 'binary-utils.js', version: RUNTIME_VERSION });
  }
  factoryDeps.push({ file: 'shared-runtime.js', version: RUNTIME_VERSION });

  var manifest = (ir.inferredFeatures && ir.inferredFeatures.factoryManifest) || [];
  manifest.forEach(function (filename) {
    factoryDeps.push({ file: filename, version: RUNTIME_VERSION });
  });

  ir.requires = { factories: factoryDeps };

  // -- 7. Serialize and sign lesson data ---------------------------------------
  var dataString = JSON.stringify(ir);
  var signature  = signContent(dataString, options.deviceId, options.privateKey);

  // -- 8. Read and encode the Hub's Ed25519 public key (Phase 4) --------------
  // This is the key that the browser uses to verify the signature.
  // It must match the private key used to sign above.
  var publicKeySpki = readPublicKeySpki(options.publicKey);

  if (options.deviceId && !publicKeySpki) {
    console.warn('\u26A0\uFE0F  Device binding requested but public key not available.');
    console.warn('   Runtime verification will fail. Pass --public-key <path>.');
  }

  if (publicKeySpki) {
    console.log('[HTML] Public key embedded (SPKI DER, ' +
      Buffer.from(publicKeySpki, 'base64').length + ' bytes)');
  }

  // -- 9. Assemble lesson-specific script block (shared with hub-transform) ----
  var lessonScript = lessonAssembly.buildLessonScript(ir, {
    signature:       signature,
    publicKeySpki:   publicKeySpki || '',
    deviceId:        options.deviceId || '',
    factoryLoaderJs: factoryLoaderJs,
    playerJs:        playerJs
  });

  // -- 10. Assemble HTML -------------------------------------------------------
  var html = [
    '<!DOCTYPE html>',
    '<html lang="' + escapeHtml((ir.meta && ir.meta.language) || 'en') + '">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">',
    '  <meta name="theme-color" content="#1a1a2e">',
    '  <title>' + escapeHtml((ir.meta && ir.meta.title) || 'AGNI Lesson') + '</title>',
    '  <style>' + styles + '</style>',
    '</head>',
    '<body>',
    '  <div id="loading">Loading lesson\u2026</div>',
    '  <div id="app"></div>',
    '  <script>',
    lessonScript,
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');

  // -- 11. Write lesson HTML ---------------------------------------------------
  fs.writeFileSync(options.output, html);

  var sizeKB = (Buffer.byteLength(html) / 1024).toFixed(1);
  console.log('\u2705 Lesson HTML: ' + options.output + ' (' + sizeKB + ' KB)');

  if (parseFloat(sizeKB) > 500) {
    console.warn('\u26A0\uFE0F  Lesson HTML exceeds 500KB (' + sizeKB + ' KB)');
  }
}


/**
 * Escape HTML special characters for attribute and text node use.
 * @param  {string} str
 * @returns {string}
 */
function escapeHtml(str) {
  if (!str) return '';
  return str
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&#039;');
}


module.exports = buildHtml;
